### ISSUE TITLE
Great project - option to compile one simple test.swift file instead of a project?

### ISSUE THREAD

**Issue by waelsaad** [nisargjhaveri/vscode-ios-debug#1]
Hi Nisarg,

I love this project, its pretty cool. 

I am just wondering if there is a way to simply compile a single test.swift file instead of a whole project and see output int the console?

**Comment by waelsaad** [comment]
Actually I got what I am after also, if its possibel to compile a list of say 2 or 3 swift files in one folder (Not a project). 

Example here:-

http://sgeos.github.io/swift/2016/02/08/getting-started-with-multi-file-command-line-swift.html

**Comment by nisargjhaveri** [comment]
I guess you found the solution from the link you sent. 

Also this extension currently doesn't help in building ios projects, that is done with tasks set up to call xcodebuild directly anyway. I'll close this issue for now.

**Comment by markst** [comment]
@waelsaad you can create a task to generate a xcode project from a swift package:
```
swift package generate-xcodeproj
```

@nisargjhaveri this might interest you also: https://github.com/markst/hotreloading-vscode-ios
