### ISSUE TITLE
Failed to install and launch app on simulator when run Demo

### ISSUE THREAD

**Issue by zengweijun** [nisargjhaveri/vscode-ios-debug#2]
macOS 10.15.7 
Xcode 12.4
iphonesimulator 14.4

look up screencast.gif in demo dispay is ios14.5, is ios14.5 required?

**Comment by nisargjhaveri** [comment]
There is not such requirements as of now.

The minimum target was 14.5 by mistake for the example project. Changed it to 13.0 in a711d1c48936add3624f5dff22097ee4045a470b.

It should work now with the latest change, have a look?

**Comment by ZengWeiJun** [comment]
I have tried both my own project and the sample project and reported the same error, so I guess the reason is the version of MacOS, I will try later after macOS upgrade

**Comment by nisargjhaveri** [comment]
I've published a new version a couple of hours back. With this, you should now get some diagnostic logs in vscode > Output > iOS Debug.

Please mention those logs here? We might be able to pin-point the issue.

To my knowledge there should not be any requirement for newer macOS or Xcode for you for this to work.

**Comment by zengweijun** [comment]
Thank you very much, I have upgraded the system to MacOS Big Sur, xcode version 12.5.1, it is works normally, and it has nothing to do with the simulator iOS version, so I think macOS Big Sur may be necessary for this to work.

**Comment by kosbar** [comment]
Big Sur, Xcode 12.5.1, Visual Studio Code 1.60.2
Failed to install app on device.
I have build with 
`"xcodebuild -workspace XXXX.xcworkspace -scheme XXXX SYMROOT=XXXX/build/"`
and use plugin with configuration:
```
{
            "name": "Launch App",
            "type": "lldb",
            "request": "launch",
            "program": "${workspaceFolder}/XXXXX/build/Debug-iphoneos/XXXX.app",
            "iosBundleId": "com.XXXXXXX",
            "iosTarget": "select",
}
```
plugin start copy  everything from **build/Debug-iphoneos/** folder and  end with error while process .app file

**Comment by nisargjhaveri** [comment]
@kosbar Could you please try to get the output from vscode > Output > iOS Debug and post here? That might help me debug this better.

**Comment by nisargjhaveri** [comment]
@santosa3-ppb Yes, it is possible to debug swift apps as well using this. Please create a new issue if you're facing any problems with that?

**Comment by nisargjhaveri** [comment]
Stale and not repro. Closing. Feel free to reopen if this is still happening with more info.
